### ISSUE TITLE
promblem apex 23.1.0

### ISSUE THREAD

**Issue by lucbind** [aghili65/OracleApexJsonViewer#1]
I can't able to run on apex 23.1.0

I imported the plugin 
I create an item json_viewr type (P6_PRETTY)
I use button to copy value from an item(P6_JSON) to the new item (P6_PRETTY) by js. apex.item( "P6_JSON" ).getValue()
but nothing happend

**Comment by lucbind** [comment]
taxError: Unexpected end of JSON input
    at Function.parse [as parseJSON] (<anonymous>)
    at new JsonViewer (json-viewer.js:22:22)
    at HTMLDivElement.<anonymous> (json-viewer.js:17:13)
    at Function.each (desktop_all.min.js?v=23.1.0:2:3003)
    at S.fn.init.each (desktop_all.min.js?v=23.1.0:2:1481)
    at $.fn.jsonview (json-viewer.js:6:21)
    at cancellare?session=115452955960699:293:60
    at HTMLDocument.<anonymous> (cancellare?session=115452955960699:293:75)
    at e.init (desktop_all.min.js?v=23.1.0:20:5718)
    at HTMLDocument.<anonymous> (cancellare?session=115452955960699:290:11)
e
